config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get 'welcome/index'

  get 'about' => 'welcome#about'

  get 'contact' => 'welcome#contact'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@homeland = 'America'
  	@countries = ['Germany', 'England', 'Canada', 'Mexico']
  	@pictures = ['island.jpg', 'maldivesatnight.jpg', 'maldivessky.jpg', 'maldiveshut.jpg']
    @united_states = {"capital_city" => "Washington, DC", 
                     "favorite_city" => "Asheville, NC", 
                     "favorite_state" => "Oregon", 
                     "flag_colors" => ["red", "white", "blue"]}
  end


  def about
  	   @color = params[:color]
       @size = params[:size].to_i
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Travel</title>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	
	<%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" %>

	<%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css" %>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>

	<!-- Latest compiled and minified CSS -->


	<!-- Latest compiled and minified JavaScript -->
	<%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" %>

</head>
<body>
	<nav class="navbar navbar-default">
		<div class="container-fluid">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="#">Brand</a>
			</div>

			<!-- Collect the nav links, forms, and other content for toggling -->
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav">
				</ul>
				<ul class="nav navbar-nav navbar-right">
					<li><%= link_to "Travel", root_path, class: "navbar-brand" %></li>
					<li><%= link_to "About", about_path %></li>
					<li><%= link_to "Contact", contact_path %></li>
				</ul>
			</div><!-- /.navbar-collapse -->
		</div><!-- /.container-fluid -->
	</nav>

	<div class="container">
		<%= yield %>
	</div>

</body>
</html>

app/views/welcome/about.html.erb
<h1>About me</h1>
<p>Lots of interesting stuffs.</p>
<p>My favorite color is <%= @color %></p>
<% if @size > 12 %>
  <p>I have HUGE feet.</p>
<% else %>
  <p>My shoe size is <%= @size %></p>
<% end %>
<style>
  body {
    background: <%= @color %>;
  }
</style>

<h1>About Me</h1>
<p>Lots of interesting stuffs.</p>
<%= link_to "Blue", about_path(color: "blue"), class: "btn btn-primary" %>
<%= link_to "Red", about_path(color: "red"), class: "btn btn-primary" %>

app/views/welcome/contact.html.erb
<h1>Welcome#contact</h1>
<p>Find me in app/views/welcome/contact.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome to my Travel Site</h1>
<p>This is my very awesome travel site.</p>

<p>My homeland is <%= @homeland %>.</p>
<p>
	<ul>
	  <% @countries.each do |country| %>
	    <li><%= country %></li>
	  <% end %>
	</ul>
</p>
<% @pictures.each do |picture| %>
<%= image_tag picture, class: "img-responsive" %>
	<% end %>

<table class="table">
  <tr>
    <% @united_states.each do |key,value| %>
	  <th><%= key.titleize %></th>
    <% end %>
  </tr>
  <tr>
    <% @united_states.each do |key,value| %>      
      <% if value.kind_of?(Array) %>
          <td><%= value.join(", ") %></td>
      <% else %>
         <td><%= value %></td>
      <% end %> 
    <% end %>
  </tr>
</table>